### ISSUE TITLE
Toggle net rate

### ISSUE THREAD

**Issue by wiltso** [raiguard/Factorio-RateCalculator#81] opened 2021-12-14 21:54 UTC
### Add a toggle button to remove the net rates

When the net rate isn't showing it would also recalculate how much materials are required, Say you have a area that is producing engines from iron plate and steel, if you in this area have more assembly machines for pipes then needed you will right now see the positive net rate and also that it would require more iron plates, but if you where to toggle off the net rate you would only see how many iron plates are required for the engines and not including for the surplus of pipes. Hope this description is understandable.

**Comment by raiguard** [comment] 2021-12-14 22:40
Duplicate of #17. This isn't nearly as straightforward as it would seem, and is out of scope for this mod. Use factory planner or helmod if you want exact ratios.

**Closed by raiguard** 2021-12-14 22:40 UTC
Labels: enhancement
