### ISSUE TITLE
Crash in 1.1.5

### ISSUE THREAD

**Issue by DrRaphello** [raiguard/Factorio-RateCalculator#38] opened 2020-12-07 18:37 UTC
The mod Rate Calculator (2.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RateCalculator::on_tick (ID 0)
__flib__/gui-beta.lua:136: attempt to index local 'elem' (a nil value)
stack traceback:
	__flib__/gui-beta.lua:136: in function 'recursive_update'
	__flib__/gui-beta.lua:165: in function 'update'
	__RateCalculator__/scripts/gui/selection.lua:379: in function 'update'
	__RateCalculator__/scripts/selection-tool.lua:166: in function 'iterate'
	__RateCalculator__/control.lua:167: in function <__RateCalculator__/control.lua:164>

**Comment by DrRaphello** [comment] 2020-12-07 18:40
Upgraded mod to 2.0.1 and now it even crashes when menu shows up after starting Factorio:

The mod Rate Calculator (2.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RateCalculator::on_configuration_changed
__RateCalculator__/scripts/gui/selection.lua:219: attempt to index field 'rates' (a nil value)
stack traceback:
	__RateCalculator__/scripts/gui/selection.lua:219: in function 'destroy'
	__RateCalculator__/scripts/player-data.lua:21: in function 'refresh'
	__RateCalculator__/control.lua:62: in function <__RateCalculator__/control.lua:52>

**Comment by raiguard** [comment] 2020-12-07 18:48
Calling this a duplicate of #37 since that one was posted less than a minute earlier.

I'm an idiot, this is a stupid crash. Ugh.

**Closed by raiguard** 2020-12-07 18:48 UTC
