### ISSUE TITLE
Crash in 2.0.0

### ISSUE THREAD

**Issue by flexoo** [raiguard/Factorio-RateCalculator#35] opened 2020-12-07 14:54 UTC
There are two ways to this crash:

1. Select some trees --> crash
or
2. Select some trees, change measurement to pollution --> crash

![crash](https://user-images.githubusercontent.com/13826740/101365649-f8c9e780-389b-11eb-9441-5219d85e53f1.png)

**Comment by raiguard** [comment] 2020-12-07 16:11
Duplicate of #32

**Closed by raiguard** 2020-12-07 16:11 UTC
Labels: bug
