### ISSUE TITLE
bug at  game load

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-RateCalculator#51] opened 2020-12-27 02:24 UTC
#### Describe the Bug

load game with Industrial Revolution mod as well and you get loading game error

#### To Reproduce

load game with Industrial Revolution mod as well and you get this
https://imgur.com/a/85SlBuz

there is no save file as the game doesn't load.  npuldon

**Comment by raiguard** [comment] 2020-12-27 06:20
This was already fixed, please update the mod.

Duplicate of #50

**Closed by raiguard** 2020-12-27 06:20 UTC
Labels: bug
