### ISSUE TITLE
it doesn't calculate the effect of beacon's modules if the beacon is not powered

### ISSUE THREAD

**Issue by MrYzsd** [raiguard/Factorio-RateCalculator#49] opened 2020-12-22 01:27 UTC
#### Describe the Bug

It doesn't calculate the effect of beacon's modules if the beacon is not powered

#### To Reproduce

1) put 2 pairs assembling machine+beacone and power one pair only. 
2) put prod modules in beacons and calculate the output of every pair, you will see that it calculates the only where beacon is powered (doesn't' matter if assembling machine is powered or not)
3) put green modules in beacons and calculate the power consumption of every pair, you will see that it calculates the only where a beacon is powered (doesn't' matter if assembling machine is powered or not)

let me know if you can't reproduce it and need save and log

p.s. I like your mod a lot, but have to keep using Max Rare calculator as it doesn't' have such bug. Hope you can fix it :)

**Comment by raiguard** [comment] 2020-12-22 01:37
Duplicate of #23, will not be fixed.

**Closed by raiguard** 2020-12-22 01:37 UTC
Labels: bug
